#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_12
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_9
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_52
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_51
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_50

#define BUILTIN_LED_GPIO        GPIO_NUM_3
#define BOOT_BUTTON_GPIO        GPIO_NUM_35

#endif // _BOARD_CONFIG_H_
